plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'dagger.hilt.android.plugin'
}

apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-parcelize'

android {
    namespace 'br.com.douglasmotta.whitelabeltutorial' // Adicione esta linha
    compileSdk 35

    defaultConfig {
        applicationId "br.com.douglasmotta.whitelabeltutorial"
        minSdkVersion 21
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
    buildFeatures {
        viewBinding true
    }

    flavorDimensions 'product', 'side'
    productFlavors {
        bike {
            dimension = 'product'
            applicationIdSuffix ".bike"
            manifestPlaceholders.appName = "Bike"
        }
        car {
            dimension = 'product'
            applicationIdSuffix ".car"
            manifestPlaceholders.appName = "Car"
        }
        client {
            dimension 'side'
            manifestPlaceholders.appNameSuffix = ""
        }
        admin {
            dimension 'side'
            applicationIdSuffix ".admin"
            manifestPlaceholders.appNameSuffix = ".Admin"
        }
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.16.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'

    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.1.21"
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'

    def nav_version = "2.9.0"
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"

    implementation 'com.google.android.material:material:1.12.0'

    implementation platform('com.google.firebase:firebase-bom:33.14.0')
    implementation 'com.google.firebase:firebase-firestore-ktx'
    implementation 'com.google.firebase:firebase-storage-ktx'

    implementation "com.google.dagger:hilt-android:$hilt_version"
    kapt "com.google.dagger:hilt-android-compiler:$hilt_version"

    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.0'

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1'

    def glide_version = '4.16.0'
    implementation "com.github.bumptech.glide:glide:$glide_version"
    kapt "com.github.bumptech.glide:compiler:$glide_version"

    testImplementation 'junit:junit:4.13.2'

    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}

//kapt {
//    javacOptions {
//        // These options are normally set automatically via the Hilt Gradle plugin, but we
//        // set them manually to workaround a bug in the Kotlin 1.5.20
//        option("-Adagger.fastInit=ENABLED")
//        option("-Adagger.hilt.android.internal.disableAndroidSuperclassValidation=true")
//    }
//}